### ISSUE TITLE
DB2 HADR

### ISSUE THREAD

**Issue by sruffatti** [ibmdb/java-db2#2]
We are having a hard time getting DB2 HADR to work using Spring Boot 3.4.2, Hikari and Tomcat. Wondering if anyone will see this and can help out.

**Comment by kolmisra** [comment]
What issue you are facing?

**Comment by sruffatti** [comment]
HADR failover isn't working at all. We use JCC 11.5.9.0. Our config is below:

```
spring:
  datasource:
    hikari:
      validation-timeout: '1000'
      data-source-properties:
        enableSeamlessFailover: '1'
        clientRerouteAlternatePortNumber: '60000'
        clientRerouteAlternateServerName: server2dr.org.com
        retryIntervalForClientReroute: '2'
        maxRetriesForClientReroute: '30'
      connection-timeout: '5000'
      idle-timeout: '300000'
      maximum-pool-size: '10'
      max-lifetime: '600000'
      connection-test-query: ...
      minimum-idle: '5'
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    username: ...
    password: ...
    url: jdbc:db2://server1.org.com:60000/SAMPLE
```

Our app initially connects to `server1.org.com` and should fail over to `server2dr.org.com`, but it never does.
